version: '3.0'

expectations:
  population_size: 1000

actions:
# General population cohort
  generate_study_population:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition
      --index-date-range "2018-03-01 to 2021-12-31 by month" 
      --output-dir=output/measures 
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv

  generate_study_population_static_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_static --index-date-range "2019-03-01" --output-dir=output/measures/tables --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_static_2019-03-01.csv

  generate_study_population_static_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_static --index-date-range "2020-03-01" --output-dir=output/measures/tables --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_static_2020-03-01.csv
  
  generate_study_population_static_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_static --index-date-range "2021-03-01" --output-dir=output/measures/tables --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_static_2021-03-01.csv

  calculate_measures:
    run: cohortextractor:latest  generate_measures --study-definition study_definition --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_*_rate.csv
# Diabetes subpopulation
  generate_study_population_dm:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_dm
      --index-date-range "2018-03-01 to 2021-12-31 by month" 
      --output-dir=output/measures 
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_dm_*.csv

  calculate_measures_dm:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_dm --output-dir=output/measures
    needs: [generate_study_population_dm]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_dm*_rate.csv

# Respiratory subpopulation
  generate_study_population_resp:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_resp
      --index-date-range "2018-03-01 to 2021-12-31 by month" 
      --output-dir=output/measures 
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_resp_*.csv

  calculate_measures_resp:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_resp --output-dir=output/measures
    needs: [generate_study_population_resp]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_resp_*_rate.csv

  create_baseline_tables:
    run: stata-mp:latest analysis/101_baseline_tables.do
    needs: [generate_study_population_static_2019, generate_study_population_static_2020, generate_study_population_static_2021]
    outputs:
      moderately_sensitive:
        log: logs/table1_descriptives.log
        output: output/tables/baseline_table_*.csv

  graphs:
    run: stata-mp:latest analysis/102_graphs.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        log: logs/graphs.log
        output: output/graphs/line_*.svg
        data: output/graphs/line_*.csv
        graphs: output/graphs/combine*

  poisson_prep:
    run: stata-mp:latest analysis/103_poisson_prep.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        log: logs/poisson_prep.log
        output: output/cvd/an*.csv

  poisson:
    run: r:latest analysis/104_poisson.R
    needs: [poisson_prep]
    outputs:
      moderately_sensitive:
        output: output/table3.csv
        model_outpus: output/poisson_model_output.txt
        model_plot: output/poisson_modelfits.pdf