version: '3.0'

expectations:
  population_size: 1000

actions:
# General population cohort
  generate_study_population:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition
      --index-date-range "2018-03-01 to 2021-12-31 by month" 
      --output-dir=output/measures 
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv

  generate_study_population_static_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_static --index-date-range "2019-01-01" --output-dir=output/measures/tables --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_static_2019-01-01.csv

  generate_study_population_static_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_static --index-date-range "2020-01-01" --output-dir=output/measures/tables --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_static_2020-01-01.csv
  
  generate_study_population_static_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_static --index-date-range "2021-01-01" --output-dir=output/measures/tables --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_static_2021-01-01.csv

 # join_cohorts:
 #   run: >
 #       cohort-joiner:v0.0.56
 #         --lhs output/measures/input_*.csv
 #         --rhs output/input_static.csv
 #         --output-dir output/measures/joined
 #   needs: [generate_study_population, generate_study_population_static]
 #   outputs: 
 #     highly_sensitive:
 #       cohort: output/measures/joined/input_*.csv

  calculate_measures:
    run: cohortextractor:latest  generate_measures --study-definition study_definition --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_*_rate.csv
# Diabetes subpopulation
  generate_study_population_dm:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_dm
      --index-date-range "2018-03-01 to 2021-12-31 by month" 
      --output-dir=output/measures 
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_dm_*.csv

  #join_cohorts_dm:
  #  run: >
  #      cohort-joiner:v0.0.56
  #        --lhs output/measures/input_dm_*.csv
  #        --rhs output/input_static.csv
  #        --output-dir output/measures/joined
  #  needs: [generate_study_population_dm, generate_study_population_static]
  #  outputs: 
  #    highly_sensitive:
  #      cohort: output/measures/joined/input_dm_*.csv

  calculate_measures_dm:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_dm --output-dir=output/measures
    needs: [generate_study_population_dm]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_dm*_rate.csv

# Respiratory subpopulation
  generate_study_population_resp:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_resp
      --index-date-range "2018-03-01 to 2021-12-31 by month" 
      --output-dir=output/measures 
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_resp_*.csv

  #join_cohorts_resp:
  #  run: >
  #      cohort-joiner:v0.0.56
  #        --lhs output/measures/input_resp_*.csv
  #        --rhs output/input_static.csv
  #        --output-dir output/measures/joined
  #  needs: [generate_study_population_resp, generate_study_population_static]
  #  outputs: 
  #    highly_sensitive:
  #      cohort: output/measures/joined/input_resp_*.csv

  calculate_measures_resp:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_resp --output-dir=output/measures
    needs: [generate_study_population_resp]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_resp_*_rate.csv

  create_baseline_tables:
    run: stata-mp:latest analysis/101_baseline_tables.do
    needs: [generate_study_population_static_2019, generate_study_population_static_2020, generate_study_population_static_2021]
    outputs:
      moderately_sensitive:
        log: logs/table1_descriptives.log
        output: output/tables/baseline_table_*.csv

  graphs:
    run: stata-mp:latest analysis/102_graphs.do
    needs: [calculate_measures, calculate_measures_dm, calculate_measures_resp]
    outputs:
      moderately_sensitive:
        log: logs/graphs.log
        output: output/graphs/line_*.svg
        data: output/graphs/line_*.csv

 #check:
  #  run: stata-mp:latest analysis/data_check.do
   # needs: [generate_study_population_dm, join_cohorts_dm]
    #outputs:
     # moderately_sensitive:
      #  log: logs/check.log